###############################################################################
# IMPORTS
###############################################################################
import os, math, argparse, json, numpy as np
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

# Diffusers Stable Diffusion pipeline
from diffusers import StableDiffusionPipeline
from diffusers.optimization import get_cosine_schedule_with_warmup

# PEFT → Parameter Efficient Fine-Tuning (LoRA)
from peft import LoraConfig, get_peft_model


###############################################################################
# DATASET CLASS — Loads JSONL dataset created earlier
###############################################################################
class InstrDataset(Dataset):
    def __init__(self, jsonl, size=512):
        """
        jsonl : path to train.jsonl file generated by dataset_prep.py
        size  : output resolution for training images (square)
        """
        # Load each line of jsonl as a Python dict
        self.items = [json.loads(l) for l in open(jsonl, "r", encoding="utf-8")]
        self.size = size

    def __len__(self):
        return len(self.items)

    def __getitem__(self, idx):
        """
        Returns:
            - instruction: text prompt/instruction
            - target: resized ground truth image (PIL)
        """
        ex = self.items[idx]
        instr = ex["instruction"]

        # Load and resize target image
        tgt = Image.open(ex["target_image"]).convert("RGB").resize((self.size, self.size))

        return {"instruction": instr, "target": tgt}


###############################################################################
# collate() — DataLoader helper (no special batching needed)
###############################################################################
def collate(batch):
    """Simple collate since images and texts are variable-length."""
    return batch


###############################################################################
# MAIN TRAINING LOOP
###############################################################################
def main(args):
    ###############################################################################
    # DEVICE SELECTION (MPS for Mac, CUDA, CPU)
    ###############################################################################
    device = (
        "mps" if torch.backends.mps.is_available()
        else ("cuda" if torch.cuda.is_available() else "cpu")
    )

    dtype = torch.float32  # MPS requires float32 for stability

    ###############################################################################
    # LOAD BASE STABLE DIFFUSION MODEL
    ###############################################################################
    pipe = StableDiffusionPipeline.from_pretrained(
        args.base_model,
        torch_dtype=dtype,
        use_safetensors=True
    ).to(device)

    ###############################################################################
    # SETUP LoRA ON UNet (cross-attention layers)
    ###############################################################################
    # These are the modules inside UNet to apply LoRA to
    target_modules = ["to_q", "to_k", "to_v", "to_out.0"]

    # Configure LoRA
    lora = LoraConfig(
        r=args.rank,              # LoRA rank
        lora_alpha=args.alpha,    # Scaling factor
        lora_dropout=args.dropout,
        target_modules=target_modules,
        bias="none",
        task_type="UNET_TS"       # UNet timestep conditioning
    )

    # Inject LoRA layers into the UNet
    pipe.unet = get_peft_model(pipe.unet, lora)

    ###############################################################################
    # LOAD DATASET
    ###############################################################################
    ds = InstrDataset(args.train_jsonl, size=args.resolution)

    dl = DataLoader(
        ds,
        batch_size=args.bs,
        shuffle=True,
        collate_fn=collate
    )

    ###############################################################################
    # OPTIMIZER + LR SCHEDULER
    ###############################################################################
    opt = torch.optim.AdamW(
        pipe.unet.parameters(),
        lr=args.lr,
        weight_decay=1e-2
    )

    total_steps = args.epochs * max(1, math.ceil(len(ds) / args.bs))

    sched = get_cosine_schedule_with_warmup(
        opt,
        int(0.05 * total_steps),   # warmup = 5%
        total_steps
    )

    ###############################################################################
    # TRAINING LOOP
    ###############################################################################
    pipe.unet.train()  # Put UNet into training mode

    for epoch in range(args.epochs):

        for batch in tqdm(dl, desc=f"epoch {epoch+1}/{args.epochs}"):

            ###############################################################
            # 1. Extract prompts (text instructions) and target images
            ###############################################################
            prompts = [b["instruction"] for b in batch]
            images = [b["target"] for b in batch]

            ###############################################################
            # 2. Convert images → latents via VAE encoder
            ###############################################################
            with torch.no_grad():
                # Convert PIL → tensor → [-1, 1] scaling
                imgs = torch.stack([
                    torch.from_numpy(np.array(img)).permute(2, 0, 1) / 255.
                    for img in images
                ]).to(device)

                imgs = imgs * 2 - 1  # scale to [-1, 1]

                # Encode via VAE → latent space
                latents = pipe.vae.encode(imgs).latent_dist.sample()
                latents = latents * 0.18215  # VAE scaling constant

            ###############################################################
            # 3. Sample random noise + diffusion timesteps
            ###############################################################
            noise = torch.randn_like(latents)

            timesteps = torch.randint(
                0,
                pipe.scheduler.config.num_train_timesteps,
                (latents.shape[0],),
                device=device
            ).long()

            noisy_latents = pipe.scheduler.add_noise(latents, noise, timesteps)

            ###############################################################
            # 4. Encode text prompts via CLIP text encoder
            ###############################################################
            tokens = pipe.tokenizer(
                prompts,
                padding=True,
                return_tensors="pt"
            ).input_ids.to(device)

            encoder_hidden_states = pipe.text_encoder(tokens)[0]

            ###############################################################
            # 5. UNet forward pass (predict noise)
            ###############################################################
            model_pred = pipe.unet(
                noisy_latents,
                timesteps,
                encoder_hidden_states=encoder_hidden_states
            ).sample

            ###############################################################
            # 6. MSE loss between predicted noise and true noise
            ###############################################################
            loss = torch.nn.functional.mse_loss(
                model_pred.float(),
                noise.float()
            )

            ###############################################################
            # 7. Backpropagation
            ###############################################################
            opt.zero_grad(set_to_none=True)
            loss.backward()

            # Clip gradients for stability
            torch.nn.utils.clip_grad_norm_(pipe.unet.parameters(), 1.0)

            # Update weights
            opt.step()
            sched.step()

        ###############################################################
        # 8. Save LoRA weights after each epoch
        ###############################################################
        save_dir = os.path.join(args.output_dir, f"lora_epoch_{epoch+1}")
        os.makedirs(save_dir, exist_ok=True)

        pipe.unet.save_pretrained(save_dir)
        print(f"[OK] saved LoRA -> {save_dir}")


###############################################################################
# ARGUMENT PARSER (CLI)
###############################################################################
if __name__ == "__main__":
    p = argparse.ArgumentParser()

    p.add_argument("--train_jsonl", required=True)
    p.add_argument("--base_model", default="runwayml/stable-diffusion-v1-5")
    p.add_argument("--epochs", type=int, default=1)
    p.add_argument("--bs", type=int, default=1)
    p.add_argument("--lr", type=float, default=5e-5)
    p.add_argument("--rank", type=int, default=8)
    p.add_argument("--alpha", type=int, default=16)
    p.add_argument("--dropout", type=float, default=0.05)
    p.add_argument("--resolution", type=int, default=512)
    p.add_argument("--output_dir", default="lora_out")

    args = p.parse_args()
    main(args)
